---
title: "p8105_hw5_ryw2109"
author: "Rita Wang"
date: "2024-11-15"
output: github_document
---

```{r default_setting, echo = FALSE, message = FALSE, warning = FALSE, results = 'hide'}
library(tidyverse)
library(ggplot2)
library(broom)
library(purrr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

```{r q1_a, echo = FALSE, message = FALSE, warning = FALSE}
set.seed(1) #  fixes the output.

birthday_check = function(dob){
  birthdays <- sample(1:365, dob, replace = TRUE)
    # fixed group size
    # randomly draws “birthdays” for each person
  return(any(duplicated(birthdays)))
    # checks whether there are duplicate birthdays in the group
    # returns TRUE or FALSE based on the result
}

# Running this function 10000 times for each group size between 2 and 50
  stimulation = 10000 
  group_size = 2:50

# For each group size, compute the probability that at least two people in the group will share a birthday by averaging across the 10000 simulation runs
  probability = sapply(group_size, function(n) {
    mean(replicate(stimulation, birthday_check(n)))
  })

dob_data = data.frame(group_size,probability)
  # preparing for graphing
  
# Make a plot showing the probability as a function of group size, and comment on your results.
ggplot(dob_data, aes(x = group_size, y = probability)) +
  geom_line(color = "purple") +
  geom_point(color = "#90EE90") +
  labs(
    title = "Probability of Shared Birthday VS Group Size",
    x = "Group Size",
    y = "Probability of Shared Birthday"
  )
```

Given a function that computes the probability that at least two people share a birthday for a fixed group size between 2 and 50, after running 10,000 times, the probability of shared birthdays as the group size increase is shown above.

```{r q2_a, echo = FALSE, message = FALSE, warning = FALSE}

```

```{r q3_a, echo = FALSE, message = FALSE, warning = FALSE}

```